# Gopkg.toml example

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.2.2"

[[constraint]]
  name = "github.com/SherClockHolmes/webpush-go"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.4"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.2"
