# Gopkg.toml example

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.2.2"
